#!/usr/bin/env python

import sys
from gitlatexhooks import publish_pdf, git_multimail

(pdf, pdfdiff, gitdiff, gitlog) = publish_pdf(sys.argv[1],
                                              sys.argv[2],
                                              sys.argv[3])

git_multimail.NEW_REVISIONS_TEMPLATE = """\
The %(tot)s revisions listed above as "new" are entirely new to
this repository.  The revisions listed as "adds" were already present
in the repository and have only been added to this reference.

For your convenience, a pdf of the latex source as well as a
latexdiff pdf is available here:

LaTeX PDF : {pdfurl}
LaTeX DIFF: {pdfdiffurl}
GIT DIFF  : {gitdiffurl}
GIT LOG   : {gitlogurl}

""".format(pdfurl=pdf, pdfdiffurl=pdfdiff,
           gitdiffurl=gitdiff, gitlogurl=gitlog)


# Specify which "git config" section contains the configuration for
# git-multimail:
config = git_multimail.Config('multimailhook')
# Select the type of environment:
environment = git_multimail.GenericEnvironment(config=config)
# Choose the method of sending emails based on the git config:
mailer = git_multimail.choose_mailer(config, environment)
# Send emails
git_multimail.run_as_update_hook(environment, mailer, sys.argv[1],
                                 sys.argv[2], sys.argv[3])
